import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
  title: 'Finteck App',
  description: 'Generated by Finteck',
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* Include metadata in the head section */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
};

export default Layout;
